server:
  port: 9090

#Muskan System
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: system
    password: saksham6
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect
#spring:
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521:xe
#    username: system
#    password: 12345
#    driver-class-name: oracle.jdbc.driver.OracleDriver
# 
#  jpa:
#    generate-ddl: false
#    show-sql: true
#    database-platform: org.hibernate.dialect.OracleDialect
# 
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger