name: Backend CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # ===================== BUILD =====================
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Maven (skip tests)
        run: mvn clean package -DskipTests

      - name: Upload build artifact (JAR)
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: target/*.jar
          retention-days: 30

  # ===================== TEST =====================
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run Unit Tests
        run: mvn test

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports

  # ===================== PACKAGE =====================
  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Package JAR (skip tests)
        run: mvn clean package -DskipTests

      - name: Upload Packaged JAR
        uses: actions/upload-artifact@v4
        with:
          name: packaged-jar
          path: target/*.jar
          retention-days: 7

  # ===================== DEPLOY =====================
  deploy:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Download Packaged JAR
        uses: actions/download-artifact@v4
        with:
          name: packaged-jar
          path: target/

      - name: Run JAR
        run: |
          nohup java -jar target/*.jar > app.log 2>&1 &
          sleep 20
          curl -f http://localhost:9090/health || exit 1
          echo "✅ Backend running at http://localhost:9090"
