name: Backend CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 👇 Build jar but skip tests (Oracle DB not available in GitHub Actions)
      - name: Build JAR (skip tests)
        run: mvn clean package -DskipTests

      # 👇 Upload the JAR so you can download it from the Actions tab
      - name: Upload build artifact (JAR)
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: target/*.jar
          retention-days: 30
